name: driverwatch
description: "Protótipo de monitoramento de motorista com IA"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Câmera e permissões
  camera: 0.10.5
  permission_handler: ^11.0.0

  # Detecção facial por Hardware (Edge Computing)
  google_mlkit_face_detection: ^0.13.2

  # Sensores Físicos de Telemetria
  sensors_plus: ^6.0.0

  # Alarme sonoro e Síntese de Voz por IA
  flutter_ringtone_player: ^4.0.0
  flutter_tts: ^4.0.2

  # Pacote para fazer ligações DIRETAS ignorando o discador
  flutter_phone_direct_caller: ^2.1.1

  # Alerta tátil háptico
  vibration: ^3.1.8

  # Ícones
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true